image: jekyll/jekyll

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

#before_script:
#  - bundle install

test:
  stage: test
  script:
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
